---
sidebar: sidebar 
keywords: Cyber vault, cybervault, cyber-vault, data protection, security, ransomware, ONTAP, hardening 
permalink: cyber-vault/ontap-cyber-vault-interop.html 
summary: 網路保險庫互通性 
---
= 網路保險庫互通性
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP硬體和軟體可用於建立網路保險庫配置。



== ONTAP硬體建議

所有ONTAP統一實體陣列均可用於網路保險庫實作。

* FAS混合儲存提供了最具成本效益的解決方案。
* AFF C 系列提供最高效的耗電量和密度。
* AFF A 系列是效能最高的平台，提供最佳的 RTO。隨著我們最新AFF A 系列的發布，該平台將提供最佳的儲存效率，同時不影響效能。




== ONTAP軟體建議

從ONTAP 9.14.1 開始，您可以在SnapMirror關係的SnapMirror政策中為特定SnapMirror標籤指定保留期，以便從來源磁碟區到目標磁碟區複製的 Snapshot 副本保留規則中指定的保留期。如果未指定保留期，則使用目標磁碟區的預設保留期。

從ONTAP 9.13.1 開始，您可以透過建立FlexClone並將 snaplock-type 選項設為“non-snaplock”並在執行磁碟區複製建立操作時將 Snapshot 副本指定為“parent-snapshot”，從而立即恢復SnapLockSnapLock庫關係的目標 SnapLock 磁碟區上的副本鎖定 Snapshot 副本。詳細了解link:https://docs.netapp.com/us-en/ontap/volumes/create-flexclone-task.html?q=volume+clone["建立具有SnapLock類型的FlexClone磁碟區"^] 。



== MetroCluster配置

對於MetroCluster配置，您應該注意以下事項：

* 您只能在同步來源 SVM 之間建立SnapVault關係，而不能在同步來源 SVM 和同步目標 SVM 之間建立 SnapVault 關係。
* 您可以建立從同步來源 SVM 上的磁碟區到資料服務 SVM 的SnapVault關係。
* 您可以建立從資料服務 SVM 上的磁碟區到同步來源 SVM 上的 DP 磁碟區的SnapVault關係。

