---
sidebar: sidebar 
permalink: cyber-vault/ontap-cyber-vault-ps-consider.html 
keywords: Cyber vault, powershell, script, configuration, validation, hardening 
summary: 這是用於配置、強化和驗證基於ONTAP的網路保險庫的NetApp ONTAP解決方案 
---
= 其他注意事項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在設計和部署基於ONTAP 的網路保險庫時，還需要考慮其他因素。



== 容量大小考慮因素

ONTAP Cyber Vault 目標磁碟區所需的磁碟空間量取決於多種因素，其中最重要的是來源磁碟區中資料的變化率。目標磁碟區上的備份計畫和快照計畫都會影響目標磁碟區上的磁碟使用情況，而來源磁碟區上的變更率可能不會保持恆定。最好提供額外的儲存容量緩衝區，以滿足未來最終用戶或應用程式行為變化的需求。

在ONTAP中確定 1 個月保留關係的大小需要根據多種因素計算儲存需求，包括主資料集的大小、資料變化率（每日變化率）以及重複資料刪除和壓縮節省（如果適用）。

以下是逐步方法：

第一步是了解使用網路保險庫保護的來源磁碟區的大小。這是最初複製到網路保險庫目的地的基本資料量。接下來，估計資料集的每日變化率。這是每天變化的數據百分比。充分了解資料的動態性至關重要。

例如：

* 主資料集大小 = 5TB
* 每日變化率=5%（0.05）
* 重複資料刪除和壓縮效率 = 50% (0.50)


現在，讓我們來看看計算過程：

* 計算每日數據變化率：
+
`Changed data per day = 5000 * 5% = 250GB`

* 計算30天的總變化數據：
+
`Total changed data in 30 days = 250 GB * 30 = 7.5TB`

* 計算所需的總儲存量：
+
`TOTAL = 5TB + 7.5TB = 12.5TB`

* 應用重複資料刪除和壓縮節省：
+
`EFFECTIVE = 12.5TB * 50% = 6.25TB`



*儲存需求摘要*

* 如果效率不高：儲存 30 天的網路保險庫資料將需要 *12.5TB*。
* 效率為 50%：重複資料刪除和壓縮後需要 *6.25TB* 的儲存空間。



NOTE: 快照副本可能會因元資料而產生額外的開銷，但這通常很小。


NOTE: 如果每天進行多次備份，則根據每天拍攝的 Snapshot 副本數量調整計算。


NOTE: 考慮資料隨時間的成長，以確保規模適合未來。



== 對主要/源的性能影響

由於資料傳輸是一種拉取操作，因此對主儲存效能的影響可能會因工作負載、資料量和備份頻率而異。然而，由於資料傳輸旨在將資料保護和備份任務卸載到網路保險庫儲存系統，因此對主系統的整體效能影響通常是適度且可控的。在初始關係設定和第一次完整備份期間，大量資料從主系統傳輸到網路保險庫系統（ SnapLock Compliance磁碟區）。這會導致主系統的網路流量和 I/O 負載增加。初始完整備份完成後， ONTAP只需要追蹤並傳輸自上次備份以來發生變化的區塊。與初始複製相比，這會導致 I/O 負載小得多。增量更新效率高，對主儲存效能的影響最小。保險庫進程在後台運行，從而減少了乾擾主系統生產工作負載的可能性。

* 確保儲存系統有足夠的資源（CPU、記憶體和 IOP）來處理額外的負載，從而減輕效能影響。

